### ISSUE TITLE
Faraday 2.7.2 GuiApp ERROR

### ISSUE THREAD

**Issue by Hankhh** [infobyte/faraday#257]
Hi Guys,

I just installed the latest version of Faraday(2.7.2) and I did the right configuration on ~/.faraday/config/user.xml and ~/.faraday/config/service.ini and service.ini is pointing to the Couchdb with the correct configuration. Couchdb and faraday-server are apparently working fine but I got the following messages everytime I ran faraday.py 

faraday.GuiApp - ERROR - Your last workspace untitled is not accessible, check the configuration.
faraday.GuiApp - ERROR - You may try and go to ~/.faraday/config/user.xml to set a valid couch_uri and last_workspace
faraday.GuiApp - ERROR - Workspace untitled wasn't found

I also tried to resolve the issue by deleting the entire ~/.faraday directory using rm -rf ~/.faraday/ and created a set of fresh service.ini config.xml and user.xml file, again it did not work!

I'm running Faraday 2.7.2 and CouchDB 1.7.1 on an Ubuntu docker. Any help would be greatly appreciated!
Thanks.

**Comment by Hankhh** [comment]
I resolved it myself! :)

**Comment by montive** [comment]
Hi there. 
Let's us know if you need any help!

**Comment by xiaoyan1985** [comment]
Hi, would you tell me how to resolve this problem? I met the same problem.
Thanks.

**Comment by Hankhh** [comment]
Resolving Last Workspace Error:

	- Remove current faraday configuration files using rm ~/.faraday/config/
	- Configure new service.ini, config.xml and user.xml files
	- Do the right configurations on CouchDB and Faraday-server server.ini 
	- Login to CouchDB through its web interface with admin credentials and stay logged in
          (http://X.X.X.X:5984/_utils/)
	- Then go to http://X.X.X.X:5985/_ui and then create a new workspace e.g. "test"
	-  Go to the ~/.faraday/config/user.xml and change the "last workspace" same as the one you already created on the previous step through web UI 
	 <last_workspace>test</last_workspace>
	- Restart Faraday server and CouchDB service and then run the faraday client 

The issue should be resolved now!

**Comment by WinnaZ** [comment]
xiaoyan1985 ,
Let us ñnow if you could solve the problem or if you need our assistance.
Cheers!

**Comment by xiaoyan1985** [comment]
Thanks.
It is the same as before, as I restart pods for DB and Faraday Server on openshift platform.
Maybe the source is not apply to openshift ?

**Comment by WinnaZ** [comment]
Hi there @xiaoyan1985 ,
Have you followed all the steps Hankhhn described (just 2 messages above) and you are still having the issue?
Is the traceback exactly the same as it was before? or are you getting a different error message?

**Comment by xiaoyan1985** [comment]
We avoid the problem by changing source.
Thank you very much.

**Comment by WinnaZ** [comment]
i'm glad to hear you made it work,
If you had any other doubt or issue don't hesitate to contact us again!
