### ISSUE TITLE
Faraday cli-client not working, the Server is up along with Web-UI on Parrot OS

### ISSUE THREAD

**Issue by sumgro** [infobyte/faraday#280]
2018-09-19 12:27:35,428 - faraday.launcher - INFO [faraday.py:404 -          printBanner() ]  Starting Faraday IDE.
2018-09-19 12:27:35,428 - faraday.launcher - INFO [faraday.py:355 -   checkConfiguration() ]  Checking configuration.
2018-09-19 12:27:35,429 - faraday.launcher - INFO [faraday.py:356 -   checkConfiguration() ]  Setting up plugins.
2018-09-19 12:27:35,429 - faraday.launcher - INFO [faraday.py:294 -         setupPlugins() ]  Removing old plugins folder.
2018-09-19 12:27:35,452 - faraday.launcher - INFO [faraday.py:358 -   checkConfiguration() ]  Setting up ZSH integration.
2018-09-19 12:27:35,453 - faraday.launcher - INFO [faraday.py:360 -   checkConfiguration() ]  Setting up user configuration.
2018-09-19 12:27:35,453 - faraday.launcher - INFO [faraday.py:335 -       setupXMLConfig() ]  Using custom user configuration.
2018-09-19 12:27:35,453 - faraday.launcher - INFO [faraday.py:362 -   checkConfiguration() ]  Setting up icons for GTK interface.
2018-09-19 12:27:35,464 - faraday.launcher - INFO [faraday.py:218 -              setConf() ]  Setting configuration.
2018-09-19 12:27:36,382 - faraday.launcher - INFO [faraday.py:529 -                login() ]  Login successful: faraday
2018-09-19 12:27:38,416 - faraday.launcher - INFO [faraday.py:427 -         checkUpdates() ]  You have available updates. Run ./faraday.py --update to catchup!
Traceback (most recent call last):
  File "./faraday.py", line 561, in <module>
    main()
  File "./faraday.py", line 557, in main
    startFaraday()
  File "./faraday.py", line 246, in startFaraday
    from model.application import MainApplication
  File "/Tools/Reporting/faraday-dev/model/application.py", line 27, in <module>
    import apis.rest.api as restapi
  File "/Tools/Reporting/faraday-dev/apis/rest/api.py", line 15, in <module>
    from tornado.wsgi import WSGIContainer
  File "/.local/lib/python2.7/site-packages/tornado/wsgi.py", line 42, in <module>
    from tornado import web
  File "/.local/lib/python2.7/site-packages/tornado/web.py", line 85, in <module>
    from tornado import gen
  File "/.local/lib/python2.7/site-packages/tornado/gen.py", line 1298, in <module>
    import tornado.platform.asyncio
  File "/.local/lib/python2.7/site-packages/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio  # type: ignore
  File "/.local/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/.local/lib/python2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax

**Comment by WinnaZ** [comment]
which version of faraday are you running?

**Comment by sumgro** [comment]
3.0.1

**Comment by WinnaZ** [comment]
which version of Tornado are you using?

**Comment by sumgro** [comment]
Name: tornado
Version: 4.5.2

**Comment by WinnaZ** [comment]
We already fixed the bug with Tornado=5.0
What command did you run when it showed this error?

**Comment by sumgro** [comment]
./faraday.py

**Comment by montive** [comment]
Hi there.

Please, run the following command and try to execute ./faraday.py once more:

**pip2 install -r requirements.txt -U**

**Comment by sumgro** [comment]
Ran the pip2 install -r requirements.txt -U, still getting the same error.

**Comment by sumgro** [comment]
> Hi.
> 
> Can you login through the Web UI?
> 
> We haven't been able to replay this issue. Can you make a **pip freeze** and send us the output?

Yes, I'm able to access the Web UI.

Here is the pop freeze output.

$pip freeze
Warning: cannot find svn location for chirp===daily-20180815
acora==2.1
adns-python==1.2.1
alabaster==0.7.11
alembic==1.0.0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.24.0
asyncio==3.4.3
atomicwrites==1.2.1
attrs==18.2.0
autobahn==18.9.2
Automat==0.7.0
Babel==2.6.0
backdoor-factory==0.0.0
backports-abc==0.5
backports.csv==1.0.6
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
BBQSQL==1.0
bcrypt==3.1.4
BeautifulSoup==3.2.1
beautifulsoup4==4.6.3
billiard==3.5.0.4
biplist==1.0.3
blinker==1.4
bravado-core==5.0.2
bs4==0.0.1
builtwith==1.3.3
cachetools==2.1.0
capstone==3.0.5
cbor==1.0.0
Cerberus==1.2
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
Cheetah3==3.1.0
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20180815
clearbit==0.1.7
cli-helpers==1.0.2
click==6.7
click-plugins==1.0.4
cluster==1.1.1b3
colorama==0.3.9
coloredlogs==10.0
config==0.4.0
ConfigArgParse==0.13.0
configobj==5.0.6
configparser==3.5.0b2
constantly==15.1.0
cookies==2.2.1
couchdbkit==0.6.5
cryptography==2.3.1
cycler==0.10.0
Cython==0.28.4
darts.util.lru==0.5
DateTime==4.2
decorator==4.3.0
deprecation==2.0.5
dhcpig==0.0.0
dicttoxml==1.7.4
diff-match-patch==20121119
distorm3==3.3.4
dnslib==0.9.7
dnspython==1.15.0
docutils==0.14
ds-store==1.1.2
easygui==0.96
EasyProcess==0.2.3
EditorConfig==0.12.1
emailprotectionslib==0.8.3
entrypoints==0.2.3.post3
enum34==1.1.6
esmre==0.3.1
et-xmlfile==1.0.1
fake-useragent==0.1.10
filedepot==0.5.2
filteralchemy==0.1.0
Flask==1.0.2
Flask-BabelEx==0.9.3
Flask-Classful==0.14.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
funcsigs==1.0.2
functools32==3.2.3.post2
fuse-python==0.3.1
future==0.16.0
futures==3.2.0
fuzzywuzzy==0.17.0
GDAL==2.3.1
GeoIP==1.3.2
gevent==1.3.5
gitdb2==2.0.4
GitPython==2.1.3
google==2.0.1
google-api-python-client==1.7.4
google-auth==1.5.1
google-auth-httplib2==0.0.3
greenlet==0.4.13
guess-language==0.2
gyp==0.1
Hackersh==0.2.0
halberd==0.2.4
hpack==3.0.0
html2text==2018.1.9
html5lib==1.0.1
http-parser==0.8.3
httplib2==0.11.3
humanfriendly==4.16.1
humanize==0.5.1
hyperlink==18.0.0
idna==2.7
imagesize==1.1.0
impacket==0.9.15
incremental==17.5.0
ipaddr==2.2.0
ipaddress==1.0.22
ipwhois==1.0.0
IPy==0.83
ipython==5.5.0
ipython-genutils==0.2.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.10
jsbeautifier==1.6.4
json2html==1.2.1
jsonpickle==0.9.5
jsonref==0.1
jsonrpclib==0.1.7
jsonschema==2.6.0
keepnote==0.7.8
keyring==15.0.0
keyrings.alt==3.1
killerbee==1.0
kiwisolver==1.0.1
logutils==0.3.5
lxkeymap==0.1
lxml==4.2.5
lz4==1.1.0
M2Crypto==0.27.0
mac-alias==2.0.7
Mako==1.0.7
Markdown==2.6.1
MarkupSafe==1.0
marshmallow==2.15.4
marshmallow-sqlalchemy==0.14.1
MAT==0.6.1
mate-menu==18.4.3
matplotlib==2.2.2
MechanicalSoup==0.11.0
mechanize==0.3.7
mercurial==4.7.1
metaconfig==0.1.4a1
mitmproxy==0.13
mock==2.0.0
mockito==1.1.1
monotonic==1.5
more-itertools==4.3.0
msgpack==0.5.6
msgpack-python==0.5.6
mutagen==1.40.0
MySQL-python==1.2.5
mysqlclient==1.3.10
nassl==1.1.3
ndg-httpsclient==0.4.0
netaddr==0.7.19
NetfilterQueue==0.6
netlib==0.13.1
networkx==2.1
NfSpy==1.0
nltk==3.0.1
nose==1.3.7
nplusone==1.0.0
numpy==1.14.5
nyawc==1.8.1
oauthlib==2.1.0
olefile==0.45.1
openpyxl==2.4.9
packaging==17.1
PAM==0.4.2
paramiko==2.4.0
Parsley==1.2
passlib==1.7.1
pathlib2==2.3.2
pathtools==0.1.2
pbkdf2==1.3
pbr==4.2.0
pcapy==0.10.8
pdfminer==20140328
pdfrw==0.4
Pebble==4.3.8
peepdf==0.4.1
pefile==2018.8.8
pexpect==4.6.0
pgcli==1.10.3
pgspecial==1.11.2
phply==0.9.1
pickleshare==0.7.4
Pillow==5.2.0
piplapis-python==5.1.5
pluggy==0.7.1
pockets==0.6.2
praw==6.0.0
prawcore==1.0.0
prettytable==0.7.2
prompt-toolkit==1.0.15
psutil==2.2.1
psycopg2==2.7.5
psycopg2-binary==2.7.5
py==1.6.0
py-ubjson==0.12.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pybloomfiltermmap==0.3.14
pycairo==1.16.2
pyClamd==0.4.0
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pydns==2.3.6
pydot==1.2.4
pyenchant==2.0.0
PyGithub==1.21.0
Pygments==2.2.0
PyGObject==3.30.1
pygraphviz==1.4rc1
PyHamcrest==1.9.0
pyinotify==0.9.6
PyJWT==1.6.4
pyliblzma==0.5.3
pymongo==3.7.1
pymssql==2.1.3
PyNaCl==1.2.1
PyOpenGL==3.1.0
pyOpenSSL==18.0.0
pyparsing==2.2.1
PyPDF2==1.26.0
pyperclip==1.6.4
PyRIC==0.1.6
pyrit==0.5.1
pyrtlsdr==0.2.4
pyscard==1.9.7
pyserial==3.4
PySide==1.2.2
PySocks==1.6.8
pysqlite==2.7.0
pytest==3.8.0
pytest-rerunfailures==4.1
python-dateutil==2.7.3
python-editor==1.0.3
python-Levenshtein==0.12.0
python-libnmap==0.7.0
python-magic==0.4.16
python-nmap==0.6.1
python-ntlm==1.0.1
python-slugify==1.2.6
python-snappy==0.5.3
python-Wappalyzer==0.2.2
python-whois==0.7.0
python-xlib==0.23
pythonaes==1.0
Pythonect==0.6.0
PyTrie==0.2
pytz==2018.5
pyusb==1.0.2
PyVirtualDisplay==0.2.1
PyX==0.12.1
pyxdg==0.25
PyYAML==3.13
pyzmq==17.1.0
qrcode==6.0
qt4reactor==1.0
requests==2.19.1
requests-file==1.4.3
requests-oauthlib==1.0.0
requests-toolbelt==0.8.0
responses==0.9.0
restkit==4.2.2
rfc3987==1.3.8
rfcat==1.0
rfidiot==1.0
roguehostapd==1.2.3
roman==2.0.0
rsa==4.0
ruamel.ordereddict==0.4.8
scandir==1.9.0
scapy==2.3.1
scapy-real==2.2.0.dev0
scipy==1.1.0
scrapy-fake-useragent==1.1.0
SecretStorage==2.3.1
selenium==3.14.0
service-identity==17.0.0
setproctitle==1.1.10
shodan==1.10.1
simplegeneric==0.8.1
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.11.0
slowaes==0.1a1
smmap2==2.0.4
snowballstemmer==1.2.1
socketpool==0.5.3
speaklater==1.3
specan==0.0.0
Sphinx==1.5.5
sphinx-better-theme==0.1.5
sphinxcontrib-napoleon==0.6.1
SQLAlchemy==1.2.11
sqlalchemy-schemadisplay==1.3
sqlparse==0.2.4
SSLyze==1.4.3
strict-rfc3339==0.7
subprocess32==3.5.2
swagger-spec-validator==2.4.0
tabulate==0.8.2
tblib==0.2.0
tcpwatch==1.3.1
termcolor==1.1.0
terminaltables==3.1.0
tld==0.9.1
tldextract==2.2.0
tls-parser==1.2.1
torbrowser-launcher==0.2.9
tornado==5.1.1
tqdm==4.26.0
traitlets==4.3.2
TravisPy==0.3.5
trollius==2.0.1
tweepy==3.6.0
Twisted==18.7.0
txaio==18.8.1
txsocksx==0.0.0
typing==3.6.6
u-msgpack-python==2.1
ua-parser==0.8.0
Unidecode==1.0.22
update-checker==0.16
uritemplate==3.0.0
urllib3==1.23
urwid==2.0.1
user-agents==1.1.0
uTidylib==0.3
vinetto==0.7b0
volatility==2.6
vulndb==0.1.0
vulners==1.3.0
w3af-api-client==1.1.7
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webargs==4.0.0
webcolors==1.8.1
webencodings==0.5.1
websocket-client==0.53.0
webunit==1.3.10
Werkzeug==0.14.1
wfuzz==2.2.11
whois==0.7
Whoosh==2.7.4
wifiphisher==1.4
wifite==2.2.5
win-inet-pton==1.0.1
wsaccel==0.6.2
WTForms==2.2.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.6
XlsxWriter==1.1.0
xmlbuilder==1.0
xmltodict==0.11.0
yara-python==3.8.0
zenmap==7.70
zope.interface==4.5.0

**Comment by montive** [comment]
Hi.

We replayed the issue at the moment we installed asyncio. Is it possible for you to uninstall asyncio, restart Faraday Server and try to run Faraday  Client once more?

**Comment by sumgro** [comment]
Removing asuncion did the trick and got the CLI working again.

Is that the final solution?

**Comment by montive** [comment]
We never had this issue. There most be a problem between asyncio and tornado.

Yes, if you need asyncio for something else, we recommend to use a virtualenv.

Cheers.

**Comment by montive** [comment]
You're welcome. Enjoy Faraday!
